### ISSUE TITLE
Error on iOS

### ISSUE THREAD

**Issue by gontijol** [Samir-Sattarov/User_inactivity_detector#1]
![image](https://github.com/Samir-Sattarov/User_inactivity_detector/assets/64325773/8b2158ed-2662-4740-9e2e-eb576138992e)

Error when run pod install

**Comment by gontijol** [comment]
I fix the error on the podfile, please accept the PR

**Comment by robport** [comment]
Same issue. Just merge the PR.

**Comment by gontijol** [comment]
> Same issue. Just merge the PR.

if samir wont accept in 3 days, i will upload a new package with the fix.
